# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
  "" for include hidden files
  "let g:ctrlp_show_hidden = 1
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  autocmd vimenter * NERDTree " 起動時に開く
  nnoremap <Leader>e :NERDTree<CR>  " ctrl + eで開く
'''

