# Required:
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
hook_add = '''
  "" for include hidden files
  "let g:ctrlp_show_hidden = 1
'''


